spring:
  datasource:
    url: POSTGRES_BOT_URL
    username: POSTGRES_USERNAME
    password: POSTGRES_PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      bootstrap-servers: KAFKA_BOOTSTRAP_SERVERS
      group-id: bot-consumer-group

bot:
  api-url: https://api.telegram.org
  host-url: BOT_HOST_URL
  token: BOT_TOKEN
  cert-path:

external-services:
  auth-url: LOGBOT_AUTH_URL
  server-url: LOGBOT_SERVER_URL
