spring:
  application:
    name: logbot-bot
  datasource:
    url: jdbc:postgresql://localhost:5432/logbot_bot_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: my-consumer-group

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

cache:
  time-to-live: 1h
