spring:
  application:
    name: logbot-bot

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

bot:
  api-url: https://api.telegram.org
  webhook-path: bot_webhook_path
  username: DWS_VK_LogBot
  token: bot_token

cache:
  expiration-time: 1h