spring:
  application:
    name: logbot-bot

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

telegram:
  api-url: https://api.telegram.org
  webhook-path: webhook_path
  bot-username: DWS_VK_LogBot
  bot-token: bot_token