spring:
  application:
    name: logbot-server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9093
      group-id: my-consumer-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9093


server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger