spring:
  application:
    name: logbot-server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
  kafka:
    bootstrap-servers: KAFKA_BOOTSTRAP_SERVERS

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger