spring:
  datasource:
    url: POSTGRES_BACKEND_URL
    username: POSTGRES_USERNAME
    password: POSTGRES_PASSWORD
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baselineOnMigrate: true
  kafka:
    consumer:
      bootstrap-servers: KAFKA_BOOTSTRAP_SERVERS
      group-id: my-consumer-group
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: KAFKA_BOOTSTRAP_SERVERS