spring:
  application:
    name: logbot-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: user
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

logbot:
  auth:
    code: vkontakte