spring:
  datasource:
    url: POSTGRES_SERVER_URL
    username: POSTGRES_USERNAME
    password: POSTGRES_PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

logbot:
  auth:
    code: vkontakte