name: Server deployment


on: push

env:
  TARGET_DIR: logbot-server

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
    - name: clone logbot sources
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.HOST_1 }}
        username: ${{ secrets.USERNAME_1 }}
        key: ${{ secrets.KEY_1 }}
        port: ${{ secrets.PORT_1 }}
        source: "."
        target: ${{ env.TARGET_DIR  }}

    - name: run logbot-server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST_1 }}
        username: ${{ secrets.USERNAME_1 }}
        key: ${{ secrets.KEY_1 }}
        port: ${{ secrets.PORT_1 }}
        script: cd ${{ env.TARGET_DIR  }} && ./gradlew :logbot-server:bootRun --args='--spring.profiles.active=stage' &

# https://www.kobzarev.com/programming/deploy-code-on-vps-with-gihub-actions-via-rsync/
# https://github.com/appleboy/ssh-action
# https://dev.to/miangame/how-to-automate-a-deploy-in-a-vps-with-github-actions-via-ssh-101e